<?php
/**
 * includes/classes/PriceListMark.php
 * -----------------------------------------------------------------------------
 * OK Veggies. The approved mark, painted onto a GD canvas.
 *
 * The generated lockup (assets/img/brand/lockup.svg) is a small, strict SVG:
 * an embedded raster seal and true vector wordmark paths, positioned with
 * translate and scale only. ImageMagick on shared hosting has no SVG delegate
 * to hand, so this painter reads that same file and reproduces it faithfully:
 * the seal is decoded from the exact bytes the approved file embeds (never
 * regenerated, never redrawn) and the letterforms are filled from their own
 * path data.
 *
 * It is strict on purpose. The brand assets are generated by
 * scripts/brand/generate_brand_assets.py from the seal; if a regenerated mark
 * ever carries something this painter does not know, the download fails with a
 * logged error rather than shipping a quietly wrong logo. Supported: svg, g,
 * image, path (M, L, H, V, Q, C, Z, upper and lower case), line, circle, the
 * translate and scale transforms, fill and stroke inheritance.
 * -----------------------------------------------------------------------------
 */

final class PriceListMark
{
    /** The approved lockup the documents print, per the Owner's logo harmony decision. */
    public const LOCKUP = '/assets/img/brand/lockup.svg';

    /** Fixed flattening steps for quadratic and cubic curves. */
    public const CURVE_STEPS = 10;

    /**
     * Paint a brand SVG at the requested width and return the GD image.
     * The aspect comes from the file's viewBox, never from a literal.
     *
     * @return GdImage
     */
    public static function paint(string $svgPath, int $targetWidth): object
    {
        $targetWidth = max(16, $targetWidth);
        $doc = new DOMDocument();
        libxml_use_internal_errors(true);
        if (!$doc->load($svgPath)) {
            throw new RuntimeException('The brand mark could not be read.');
        }
        $svg = $doc->getElementsByTagName('svg')->item(0);
        if (!$svg instanceof DOMElement) {
            throw new RuntimeException('The brand mark is not an SVG document.');
        }

        $viewBox = preg_split('/[\s,]+/', trim((string) $svg->getAttribute('viewBox')));
        if (count($viewBox) !== 4) {
            throw new RuntimeException('The brand mark has no viewBox to scale from.');
        }
        $vbX = (float) $viewBox[0];
        $vbY = (float) $viewBox[1];
        $vbW = (float) $viewBox[2];
        $vbH = (float) $viewBox[3];
        if ($vbW <= 0 || $vbH <= 0) {
            throw new RuntimeException('The brand mark viewBox is empty.');
        }

        $scale = $targetWidth / $vbW;
        $width = (int) ceil($vbW * $scale);
        $height = (int) ceil($vbH * $scale);

        $img = imagecreatetruecolor($width, $height);
        imagesavealpha($img, true);
        imagefill($img, 0, 0, imagecolorallocatealpha($img, 0, 0, 0, 127));

        // The identity matrix in SVG's (a b c d e f) form.
        $identity = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
        $state = ['matrix' => $identity, 'fill' => '', 'stroke' => ''];
        foreach (iterator_to_array($svg->childNodes) as $child) {
            if ($child instanceof DOMElement) {
                self::element($img, $child, $state, $scale, $vbX, $vbY);
            }
        }
        return $img;
    }

    /** Apply one element and walk its children. */
    private static function element(object $img, DOMElement $el, array $state, float $scale, float $vbX, float $vbY): void
    {
        $tag = $el->nodeName;
        if ($tag === 'defs' || $tag === '#comment') {
            return;
        }

        $state = self::inherited($el, $state);
        $matrix = self::withTransform($el, $state['matrix']);

        switch ($tag) {
            case 'g':
                foreach (iterator_to_array($el->childNodes) as $child) {
                    if ($child instanceof DOMElement) {
                        $childState = $state;
                        $childState['matrix'] = $matrix;
                        self::element($img, $child, $childState, $scale, $vbX, $vbY);
                    }
                }
                return;

            case 'image':
                self::image($img, $el, $matrix, $scale, $vbX, $vbY);
                return;

            case 'path':
                self::path($img, $el, $state, $matrix, $scale, $vbX, $vbY);
                return;

            case 'line':
                self::line($img, $el, $state, $matrix, $scale, $vbX, $vbY);
                return;

            case 'circle':
                self::circle($img, $el, $state, $matrix, $scale, $vbX, $vbY);
                return;

            case 'svg':
                return;

            default:
                throw new RuntimeException('The brand mark uses an element this painter does not know: ' . $tag);
        }
    }

    /** Element fill and stroke override the inherited ones when present. */
    private static function inherited(DOMElement $el, array $state): array
    {
        foreach (['fill' => 'fill', 'stroke' => 'stroke'] as $attr => $key) {
            $value = trim((string) $el->getAttribute($attr));
            if ($value !== '') {
                $state[$key] = strtolower($value);
            }
        }
        return $state;
    }

    /** Multiply the current matrix by the element's translate and scale list. */
    private static function withTransform(DOMElement $el, array $matrix): array
    {
        $transform = trim((string) $el->getAttribute('transform'));
        if ($transform === '') {
            return $matrix;
        }
        if (!preg_match_all('/(translate|scale)\s*\(([^)]*)\)/', $transform, $calls, PREG_SET_ORDER)) {
            throw new RuntimeException('The brand mark uses a transform this painter does not know: ' . $transform);
        }
        foreach ($calls as [$whole, $fn, $argsRaw]) {
            $args = array_map('floatval', preg_split('/[\s,]+/', trim($argsRaw)));
            if ($fn === 'translate') {
                $tx = $args[0] ?? 0.0;
                $ty = $args[1] ?? 0.0;
                $m = [1.0, 0.0, 0.0, 1.0, $tx, $ty];
            } else {
                $sx = $args[0] ?? 1.0;
                $sy = $args[1] ?? $sx;
                if ($sx === 0.0 || $sy === 0.0) {
                    throw new RuntimeException('The brand mark scales to nothing.');
                }
                $m = [$sx, 0.0, 0.0, $sy, 0.0, 0.0];
            }
            // parent x child, in SVG's column-vector convention.
            $matrix = [
                $matrix[0] * $m[0] + $matrix[2] * $m[1],
                $matrix[1] * $m[0] + $matrix[3] * $m[1],
                $matrix[0] * $m[2] + $matrix[2] * $m[3],
                $matrix[1] * $m[2] + $matrix[3] * $m[3],
                $matrix[0] * $m[4] + $matrix[2] * $m[5] + $matrix[4],
                $matrix[1] * $m[4] + $matrix[3] * $m[5] + $matrix[5],
            ];
        }
        return $matrix;
    }

    /** Map user units to device pixels: scale, then shift the viewBox away. */
    private static function toDevice(array $matrix, float $scale, float $vbX, float $vbY, float $x, float $y): array
    {
        $ux = $matrix[0] * $x + $matrix[2] * $y + $matrix[4];
        $uy = $matrix[1] * $x + $matrix[3] * $y + $matrix[5];
        return [($ux - $vbX) * $scale, ($uy - $vbY) * $scale];
    }

    /** The embedded seal, decoded from the approved file's own bytes. */
    private static function image(object $img, DOMElement $el, array $matrix, float $scale, float $vbX, float $vbY): void
    {
        $href = $el->getAttribute('href');
        if ($href === '' && $el->getAttribute('xlink:href') !== '') {
            $href = $el->getAttribute('xlink:href');
        }
        if (!preg_match('#^data:image/(png|jpeg);base64,#', $href, $m)) {
            throw new RuntimeException('The brand mark embeds an image this painter does not know.');
        }
        $blob = (string) base64_decode(substr($href, strlen($m[0])), true);
        if ($blob === '') {
            throw new RuntimeException('The brand mark embeds an unreadable image.');
        }
        $seal = @imagecreatefromstring($blob);
        if ($seal === false) {
            throw new RuntimeException('The brand mark embeds an image GD cannot decode.');
        }

        $x = (float) $el->getAttribute('x');
        $y = (float) $el->getAttribute('y');
        $w = (float) $el->getAttribute('width');
        $h = (float) $el->getAttribute('height');
        [$dx1, $dy1] = self::toDevice($matrix, $scale, $vbX, $vbY, $x, $y);
        [$dx2, $dy2] = self::toDevice($matrix, $scale, $vbX, $vbY, $x + $w, $y + $h);
        $dw = (int) round(abs($dx2 - $dx1));
        $dh = (int) round(abs($dy2 - $dy1));
        if ($dw < 1 || $dh < 1) {
            return;
        }
        imagealphablending($img, true);
        imagecopyresampled(
            $img,
            $seal,
            (int) round(min($dx1, $dx2)),
            (int) round(min($dy1, $dy2)),
            0,
            0,
            $dw,
            $dh,
            imagesx($seal),
            imagesy($seal)
        );
    }

    /** One path element: parse, flatten, fill and stroke in device pixels. */
    private static function path(object $img, DOMElement $el, array $state, array $matrix, float $scale, float $vbX, float $vbY): void
    {
        $d = $el->getAttribute('d');
        if ($d === '') {
            return;
        }
        $polylines = self::pathPolylines($d, $matrix, $scale, $vbX, $vbY);
        if ($polylines === []) {
            return;
        }

        imagealphablending($img, true);
        $fill = self::paintColour($state['fill']);
        if ($fill !== null) {
            $points = [];
            foreach ($polylines as $poly) {
                foreach ($poly as [$px, $py]) {
                    $points[] = (int) round($px);
                    $points[] = (int) round($py);
                }
            }
            if (count($points) >= 6) {
                imagefilledpolygon($img, $points, $fill);
            }
        }

        $stroke = self::paintColour($state['stroke']);
        if ($stroke !== null) {
            $width = (float) $el->getAttribute('stroke-width');
            imagesetthickness($img, max(1, (int) round($width * $scale)));
            foreach ($polylines as $poly) {
                $count = count($poly);
                for ($i = 1; $i < $count; $i++) {
                    imageline(
                        $img,
                        (int) round($poly[$i - 1][0]),
                        (int) round($poly[$i - 1][1]),
                        (int) round($poly[$i][0]),
                        (int) round($poly[$i][1]),
                        $stroke
                    );
                }
            }
            imagesetthickness($img, 1);
        }
    }

    private static function line(object $img, DOMElement $el, array $state, array $matrix, float $scale, float $vbX, float $vbY): void
    {
        $stroke = self::paintColour($state['stroke']);
        if ($stroke === null) {
            return;
        }
        [$x1, $y1] = self::toDevice($matrix, $scale, $vbX, $vbY, (float) $el->getAttribute('x1'), (float) $el->getAttribute('y1'));
        [$x2, $y2] = self::toDevice($matrix, $scale, $vbX, $vbY, (float) $el->getAttribute('x2'), (float) $el->getAttribute('y2'));
        imagealphablending($img, true);
        imagesetthickness($img, max(1, (int) round((float) $el->getAttribute('stroke-width') * $scale)));
        imageline($img, (int) round($x1), (int) round($y1), (int) round($x2), (int) round($y2), $stroke);
        if (strtolower($el->getAttribute('stroke-linecap')) === 'round') {
            $r = max(1, (int) round((float) $el->getAttribute('stroke-width') * $scale / 2));
            foreach ([[$x1, $y1], [$x2, $y2]] as [$cx, $cy]) {
                imagefilledellipse($img, (int) round($cx), (int) round($cy), $r * 2, $r * 2, $stroke);
            }
        }
        imagesetthickness($img, 1);
    }

    private static function circle(object $img, DOMElement $el, array $state, array $matrix, float $scale, float $vbX, float $vbY): void
    {
        // A circle is only drawn when the matrix keeps it a circle: no skew,
        // no rotation, and the same scale on both axes, which is all the
        // generated brand marks ever use.
        if ($matrix[1] !== 0.0 || $matrix[2] !== 0.0 || abs($matrix[0] - $matrix[3]) > 0.0001) {
            throw new RuntimeException('The brand mark scales a circle unevenly.');
        }
        [$cx, $cy] = self::toDevice($matrix, $scale, $vbX, $vbY, (float) $el->getAttribute('cx'), (float) $el->getAttribute('cy'));
        $r = (float) $el->getAttribute('r') * $scale * abs($matrix[0]);
        if ($r < 0.5) {
            return;
        }
        imagealphablending($img, true);
        $fill = self::paintColour($state['fill']);
        if ($fill !== null) {
            imagefilledellipse($img, (int) round($cx), (int) round($cy), (int) ceil($r * 2), (int) ceil($r * 2), $fill);
        }
        $stroke = self::paintColour($state['stroke']);
        if ($stroke !== null) {
            imagesetthickness($img, max(1, (int) round((float) $el->getAttribute('stroke-width') * $scale)));
            imageellipse($img, (int) round($cx), (int) round($cy), (int) ceil($r * 2), (int) ceil($r * 2), $stroke);
            imagesetthickness($img, 1);
        }
    }

    /** A hex colour packed for a truecolor target, or null for none. */
    private static function paintColour(string $value): ?int
    {
        $value = strtolower(trim($value));
        if ($value === '' || $value === 'none') {
            return null;
        }
        if (!preg_match('/^#[0-9a-f]{6}$/', $value)) {
            throw new RuntimeException('The brand mark uses a colour this painter does not know: ' . $value);
        }
        $r = (int) hexdec(substr($value, 1, 2));
        $g = (int) hexdec(substr($value, 3, 2));
        $b = (int) hexdec(substr($value, 5, 2));
        return ($r << 16) | ($g << 8) | $b;
    }

    /**
     * Turn a path string into device-space polylines. Only the commands the
     * generated brand marks use are supported; anything else is a fault, not
     * a quiet wrong shape.
     *
     * @return array<int, array<int, array{0: float, 1: float}>>
     */
    private static function pathPolylines(string $d, array $matrix, float $scale, float $vbX, float $vbY): array
    {
        if (!preg_match_all('/([MLHVQCSZTAmlhvqcszta])([^MLHVQCSZTAmlhvqcszta]*)/', $d, $tokens, PREG_SET_ORDER)) {
            return [];
        }

        $supported = ['M', 'L', 'H', 'V', 'Q', 'C', 'Z'];
        $polylines = [];
        $poly = [];
        $cx = 0.0;
        $cy = 0.0;
        $sx = 0.0;
        $sy = 0.0;
        $pt = function (float $x, float $y) use ($matrix, $scale, $vbX, $vbY): array {
            return self::toDevice($matrix, $scale, $vbX, $vbY, $x, $y);
        };
        $steps = self::CURVE_STEPS;

        foreach ($tokens as [$whole, $cmd, $argsRaw]) {
            preg_match_all('/[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/', $argsRaw, $numsRaw);
            $nums = array_map('floatval', $numsRaw[0]);
            $upper = strtoupper($cmd);
            if (!in_array($upper, $supported, true)) {
                throw new RuntimeException('The brand mark uses a path command this painter does not know: ' . $cmd);
            }
            $rel = $cmd !== $upper;
            $i = 0;
            $n = count($nums);

            // One letter may carry several coordinate sets, so each command
            // consumes its arguments until they run out.
            while ($i < $n) {
                switch ($upper) {
                    case 'M':
                        if ($i + 1 >= $n) {
                            break 2;
                        }
                        $x = $nums[$i++];
                        $y = $nums[$i++];
                        if ($rel) {
                            $x += $cx;
                            $y += $cy;
                        }
                        if ($poly !== []) {
                            $polylines[] = $poly;
                        }
                        [$cx, $cy] = [$x, $y];
                        $sx = $x;
                        $sy = $y;
                        $poly = [$pt($x, $y)];
                        $upper = 'L';
                        break;

                    case 'L':
                        if ($i + 1 >= $n) {
                            break 2;
                        }
                        $x = $nums[$i++];
                        $y = $nums[$i++];
                        if ($rel) {
                            $x += $cx;
                            $y += $cy;
                        }
                        $poly[] = $pt($x, $y);
                        $cx = $x;
                        $cy = $y;
                        break;

                    case 'H':
                        if ($i >= $n) {
                            break 2;
                        }
                        $x = $nums[$i++];
                        if ($rel) {
                            $x += $cx;
                        }
                        $poly[] = $pt($x, $cy);
                        $cx = $x;
                        break;

                    case 'V':
                        if ($i >= $n) {
                            break 2;
                        }
                        $y = $nums[$i++];
                        if ($rel) {
                            $y += $cy;
                        }
                        $poly[] = $pt($cx, $y);
                        $cy = $y;
                        break;

                    case 'Q':
                        if ($i + 3 >= $n) {
                            break 2;
                        }
                        $x1 = $nums[$i++];
                        $y1 = $nums[$i++];
                        $x = $nums[$i++];
                        $y = $nums[$i++];
                        if ($rel) {
                            $x1 += $cx;
                            $y1 += $cy;
                            $x += $cx;
                            $y += $cy;
                        }
                        for ($s = 1; $s <= $steps; $s++) {
                            $t = $s / $steps;
                            $mt = 1 - $t;
                            $poly[] = $pt(
                                $mt * $mt * $cx + 2 * $mt * $t * $x1 + $t * $t * $x,
                                $mt * $mt * $cy + 2 * $mt * $t * $y1 + $t * $t * $y
                            );
                        }
                        $cx = $x;
                        $cy = $y;
                        break;

                    case 'C':
                        if ($i + 5 >= $n) {
                            break 2;
                        }
                        $x1 = $nums[$i++];
                        $y1 = $nums[$i++];
                        $x2 = $nums[$i++];
                        $y2 = $nums[$i++];
                        $x = $nums[$i++];
                        $y = $nums[$i++];
                        if ($rel) {
                            $x1 += $cx;
                            $y1 += $cy;
                            $x2 += $cx;
                            $y2 += $cy;
                            $x += $cx;
                            $y += $cy;
                        }
                        for ($s = 1; $s <= $steps; $s++) {
                            $t = $s / $steps;
                            $mt = 1 - $t;
                            $poly[] = $pt(
                                $mt * $mt * $mt * $cx + 3 * $mt * $mt * $t * $x1 + 3 * $mt * $t * $t * $x2 + $t * $t * $t * $x,
                                $mt * $mt * $mt * $cy + 3 * $mt * $mt * $t * $y1 + 3 * $mt * $t * $t * $y2 + $t * $t * $t * $y
                            );
                        }
                        $cx = $x;
                        $cy = $y;
                        break;

                    case 'Z':
                        // Close the subpath and stop this letter's arguments.
                        // A path element may hold several M...Z runs, one per
                        // letter shape, and the foreach above brings the next
                        // letter in.
                        if ($poly !== []) {
                            $poly[] = $poly[0];
                            $polylines[] = $poly;
                            $poly = [];
                        }
                        $cx = $sx;
                        $cy = $sy;
                        break 2;

                    default:
                        break 2;
                }
            }
        }
        if ($poly !== []) {
            $polylines[] = $poly;
        }
        return $polylines;
    }
}
