<?php
/**
 * includes/classes/ProductImages.php
 * -----------------------------------------------------------------------------
 * OK Veggies. Presentation for the 24 catalogue photographs.
 *
 * The database stores the original JPEG path. WebP siblings sit next to it at
 * 400, 800 and 1200 pixels, generated by scripts/brand/optimise_catalogue_images.sh
 * so a mid-range phone never downloads a 200KB JPEG for a 175px card. The class
 * never writes; it only reports what is on disk, so a missing sibling falls
 * back to the JPEG rather than a broken image.
 *
 * Combo photos that live under uploads/ are left alone. They are not the
 * launch catalogue and have no generated siblings yet.
 */
final class ProductImages
{
    public const WIDTHS = [400, 800, 1200];

    /**
     * @return array{src:string,srcset:string,width:int,height:int,type:string}
     */
    public static function presentation(string $path): array
    {
        $path = '/' . ltrim(str_replace('\\', '/', $path), '/');
        $root = dirname(__DIR__, 2);
        $absolute = $root . $path;
        $size = is_file($absolute) ? @getimagesize($absolute) : false;
        $width = (int) ($size[0] ?? 0);
        $height = (int) ($size[1] ?? 0);
        if ($width < 1) {
            $width = 800;
            $height = 800;
        }

        $created = [];
        $info = pathinfo($path);
        $dir = (string) ($info['dirname'] ?? '');
        $stem = (string) ($info['filename'] ?? '');
        $inCatalogue = str_starts_with($path, '/assets/img/product_images/') && $stem !== '';
        if ($inCatalogue) {
            foreach (self::WIDTHS as $candidateWidth) {
                $candidate = $dir . '/' . $stem . '-' . $candidateWidth . '.webp';
                if (is_file($root . $candidate)) {
                    $created[$candidateWidth] = $candidate;
                }
            }
        }

        return [
            'src' => $path,
            'srcset' => self::srcset($created),
            'width' => $width,
            'height' => $height,
            'type' => $created !== [] ? 'image/webp' : '',
        ];
    }

    /**
     * @param array<int, string> $paths
     */
    private static function srcset(array $paths): string
    {
        $parts = [];
        foreach ($paths as $width => $path) {
            $parts[] = okv_image_url((string) $path) . ' ' . (int) $width . 'w';
        }
        return implode(', ', $parts);
    }
}
