<?php
/** Guest checkout through the real HTTP controllers on a scratch database. */
$root=dirname(__DIR__,2);require_once $root.'/includes/bootstrap.php';
if(!function_exists('curl_init')){fwrite(STDERR,"This test needs the PHP curl extension.\n");exit(2);}
const CHECKOUT_HTTP_BASE='http://127.0.0.1:8299';
$tests=0;$passed=0;
$check=static function($condition,string $label)use(&$tests,&$passed):void{$tests++;if($condition){$passed++;return;}fwrite(STDERR,"  FAIL: $label\n");};
$request=static function(string $method,string $path,?array $fields,string $jar,bool $json=true):array{
    $ch=curl_init(CHECKOUT_HTTP_BASE.$path);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$jar,CURLOPT_COOKIEFILE=>$jar,CURLOPT_FOLLOWLOCATION=>false]);
    if($method==='POST'){curl_setopt($ch,CURLOPT_POST,true);curl_setopt($ch,CURLOPT_POSTFIELDS,http_build_query($fields??[]));}
    if($json)curl_setopt($ch,CURLOPT_HTTPHEADER,['X-Requested-With: fetch','Accept: application/json']);
    $response=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$headerSize=(int)curl_getinfo($ch,CURLINFO_HEADER_SIZE);curl_close($ch);$body=$response===false?'':substr($response,$headerSize);
    return [$status,$json?(json_decode($body,true)??[]):$body];
};
$csrf=static function(string $jar)use($request):string{[, $html]=$request('GET','/shop.php',null,$jar,false);if(preg_match('/name="okv_csrf" value="([^"]+)"/',$html,$match))return $match[1];return '';};
$log='/tmp/okv_checkout_http_server.log';$server=proc_open('exec php -d display_errors=0 -S 127.0.0.1:8299 -t '.escapeshellarg($root),[0=>['pipe','r'],1=>['file',$log,'w'],2=>['file',$log,'w']],$pipes);
if(!is_resource($server)){fwrite(STDERR,"Could not start the checkout test server.\n");exit(2);} $up=false;for($i=0;$i<50;$i++){$socket=@fsockopen('127.0.0.1',8299,$errno,$error,0.2);if($socket){fclose($socket);$up=true;break;}usleep(100000);}if(!$up){proc_terminate($server);fwrite(STDERR,"The checkout test server did not come up.\n");exit(2);}
$pdo=Database::getInstance()->getConnection();$suffix=bin2hex(random_bytes(5));$email='checkout.'.$suffix.'@example.test';$beforeCart=(int)(Database::one('SELECT COALESCE(MAX(id),0) id FROM shopping_carts')['id']??0);$jar=tempnam(sys_get_temp_dir(),'okvco');$privateJar=tempnam(sys_get_temp_dir(),'okvtr');$orderId=0;$userId=0;
try{
    $product=Database::one("SELECT p.id FROM products p LEFT JOIN product_availability pa ON pa.product_id=p.id WHERE p.is_active=1 AND p.current_price_subunit>0 AND COALESCE(pa.availability_status,'available')='available' ORDER BY p.id LIMIT 1");$combo=Database::one('SELECT id FROM combo_packages WHERE is_active=1 AND price_subunit>0 ORDER BY id LIMIT 1');
    $token=$csrf($jar);$check($token!=='','storefront supplies a CSRF token');
    [$status,$body]=$request('POST','/api/v1/cart.php',['action'=>'add_product','product_id'=>$product['id'],'okv_csrf'=>$token],$jar);$check($status===200&&($body['basket_count']??0)===1,'guest adds a product');
    [$status,$body]=$request('POST','/api/v1/cart.php',['action'=>'add_combo','combo_id'=>$combo['id'],'okv_csrf'=>$token],$jar);$check($status===200&&($body['basket_count']??0)===2,'guest adds a combo');
    $customer=['action'=>'save_step','step'=>'customer','okv_csrf'=>$token,'recipient_name'=>'HTTP Checkout','recipient_phone'=>'08012345678','email'=>$email,'address_line_1'=>'1 Test Street','address_line_2'=>'','city'=>'Lagos','state'=>'Lagos','landmark'=>'Test gate','customer_type'=>'household','create_account'=>'1'];
    [$status]=$request('POST','/api/v1/checkout.php',$customer,$jar);$check($status===200,'guest customer step saves idempotently');
    [, $dates]=$request('GET','/api/v1/delivery.php?action=eligible_dates&customer_type=household',null,$jar);[, $zones]=$request('GET','/api/v1/delivery.php?action=zones',null,$jar);$date=$dates['dates'][0]['date']??'';$zone=(int)($zones['zones'][0]['id']??0);$check($date!==''&&$zone>0,'checkout receives an eligible date and active zone');
    [$status]=$request('POST','/api/v1/checkout.php',['action'=>'save_step','step'=>'delivery','okv_csrf'=>$token,'delivery_date'=>$date,'delivery_zone_id'=>$zone],$jar);$check($status===200,'delivery step saves');
    [$status,$forged]=$request('POST','/api/v1/checkout.php',['action'=>'place_order','payment_option'=>'deposit'], $jar);$check($status===419&&($forged['code']??'')==='csrf_expired','forged final submission is refused');
    [$status,$placed]=$request('POST','/api/v1/checkout.php',['action'=>'place_order','okv_csrf'=>$token,'payment_option'=>'deposit'],$jar);$orderId=(int)($placed['order_id']??0);$check($status===200&&$orderId>0,'guest places an order after explicit account consent');
    $check(str_contains((string)($placed['confirmation_url']??''),'/public/order.php?order='),'place_order returns the canonical confirmation URL');$check(str_contains((string)($placed['trail_url']??''),'/public/order.php?token='),'place_order returns the canonical trail URL');
    [$status,$retry]=$request('POST','/api/v1/checkout.php',['action'=>'place_order','okv_csrf'=>$token,'payment_option'=>'deposit'],$jar);$check($status===200&&(int)($retry['order_id']??0)===$orderId,'refresh or retry returns the same order');
    $confirmationPath=parse_url($placed['confirmation_url'],PHP_URL_PATH).'?'.parse_url($placed['confirmation_url'],PHP_URL_QUERY);[$status,$confirmation]=$request('GET',$confirmationPath,null,$jar,false);$check($status===200&&str_contains($confirmation,'Amount due'),'signed confirmation shows the amount due');$check(str_contains($confirmation,'Share on WhatsApp'),'signed confirmation can share its server-session trail token');
    $trailPath=parse_url($placed['trail_url'],PHP_URL_PATH).'?'.parse_url($placed['trail_url'],PHP_URL_QUERY);[$status,$trail]=$request('GET',$trailPath,null,$privateJar,false);$check($status===200&&str_contains($trail,'Order Trail'),'private-window token opens the Order Trail');$check(!str_contains($trail,$email)&&!str_contains($trail,'08012345678')&&!str_contains($trail,'1 Test Street'),'public trail contains no customer details');$check(!str_contains($trail,'Amount due'),'public trail does not reveal the amount due');
    [$badStatus,$badTrail]=$request('GET','/public/order.php?token=malformed',null,$privateJar,false);[$randomStatus,$randomTrail]=$request('GET','/public/order.php?token='.str_repeat('a',43),null,$privateJar,false);$check($badStatus===404&&$randomStatus===404,'malformed and random tokens both return 404');$check(str_contains($badTrail,'We could not find that order')&&str_contains($randomTrail,'We could not find that order'),'malformed and random tokens share the branded not-found response');
    $user=Database::one('SELECT id,email_verified_at FROM users WHERE email=:email',[':email'=>$email]);$userId=(int)($user['id']??0);$check($userId>0&&$user['email_verified_at']===null,'guest checkout creates an unverified household account');$payment=Database::one('SELECT status,expected_amount_subunit FROM payments WHERE order_id=:order_id',[':order_id'=>$orderId]);$order=Database::one('SELECT deposit_required_subunit FROM orders WHERE id=:id',[':id'=>$orderId]);$check($payment['status']==='unpaid'&&(int)$payment['expected_amount_subunit']===(int)$order['deposit_required_subunit'],'deposit payment remains unpaid for the required amount');
}finally{
    if($orderId>0){$itemIds=array_column(Database::all('SELECT id FROM order_items WHERE order_id=:id',[':id'=>$orderId]),'id');foreach($itemIds as $itemId)Database::run('DELETE FROM order_item_components WHERE order_item_id=:id',[':id'=>$itemId]);foreach(['payments','order_status_history','order_addresses','order_items'] as $table)Database::run("DELETE FROM $table WHERE order_id=:id",[':id'=>$orderId]);Database::run('DELETE FROM orders WHERE id=:id',[':id'=>$orderId]);}
    if($userId>0){Database::run('DELETE FROM customer_addresses WHERE user_id=:id',[':id'=>$userId]);Database::run('DELETE FROM users WHERE id=:id',[':id'=>$userId]);}Database::run('DELETE FROM shopping_carts WHERE id>:id',[':id'=>$beforeCart]);@unlink($jar);@unlink($privateJar);proc_terminate($server);
}
fwrite(STDOUT,"\n$passed / $tests assertions passed.\n");if($passed!==$tests)exit(1);fwrite(STDOUT,"All green.\n");
