<?php
okv_test_eq(320000, Checkout::total([['quantity'=>'1.000','unit_price_subunit'=>270000],['quantity'=>'0.500','unit_price_subunit'=>100000]]), 'checkout preserves snapshot subtotal maths');
$repricedSnapshot=Checkout::snapshot(['lines'=>[['quantity'=>'1.000','unit_price_subunit'=>270000],['quantity'=>'1.000','unit_price_subunit'=>300000]]]);
okv_test_eq(570000,$repricedSnapshot['subtotal_subunit'],'checkout totals old and new price snapshots separately');
okv_test_eq(270000,$repricedSnapshot['lines'][0]['unit_price_subunit'],'checkout leaves the earlier unit price unchanged');
okv_test_eq(300000,$repricedSnapshot['lines'][1]['unit_price_subunit'],'checkout keeps the newly added unit price');
okv_test_ok(Checkout::paymentAllowed('pay_on_delivery','household',true), 'activated household can pay on delivery');
okv_test_ok(!Checkout::paymentAllowed('pay_on_delivery','household',false), 'unactivated household cannot pay on delivery');
okv_test_ok(!Checkout::paymentAllowed('on_account','household',true), 'household cannot use on-account payment');
okv_test_ok(Checkout::paymentAllowed('on_account','business',true), 'business can use on-account payment');
okv_test_eq(507000, Checkout::amountDue('deposit', 1690000, 30), 'deposit amount uses the setting percentage');
okv_test_eq(1690000, Checkout::amountDue('pay_in_full', 1690000, 30), 'pay in full expects the order total');
okv_test_eq(1690000, Money::balance(1690000, 0), 'an unpaid order keeps the full balance');
okv_test_ok(Checkout::placedMatchesBasket(['placed'=>['order_id'=>10],'placed_cart_id'=>4],4),'a retry for the converted source basket returns its order');
okv_test_ok(Checkout::placedMatchesBasket(['placed'=>['order_id'=>10],'placed_cart_id'=>4],null),'a refresh after conversion returns its order');
okv_test_ok(!Checkout::placedMatchesBasket(['placed'=>['order_id'=>10],'placed_cart_id'=>4],5),'a genuinely new basket does not return the previous order');
$deliveryError=new CheckoutException('delivery_unavailable','This date is closed for stocktaking.');
okv_test_eq('delivery_unavailable',$deliveryError->getMessage(),'checkout exception keeps its fixed internal code');
okv_test_eq('This date is closed for stocktaking.',$deliveryError->customerMessage(),'checkout exception keeps separately approved customer copy');
$checkoutSession=$_SESSION??[];$_SESSION=[];Checkout::saveStep('delivery',['delivery_date'=>'2026-09-05']);
okv_test_eq('2026-09-05',Checkout::bag()['delivery']['delivery_date'],'checkout steps persist in the server session');
$_SESSION['okv_checkout']['at']=time()-7201;
okv_test_eq([],Checkout::bag(),'checkout session state expires after two hours');
$_SESSION=$checkoutSession;
$trailToken = OrderTrail::newToken();
okv_test_ok((bool) preg_match('/^[A-Za-z0-9_-]{43}$/', $trailToken), 'trail token is URL safe and 256 bit');
okv_test_eq(64, strlen(OrderTrail::hashToken($trailToken)), 'trail token hash is sha256 hex');
okv_test_ok(!OrderTrail::isValidToken('short'), 'malformed trail token is refused');
okv_test_ok(!OrderTrail::isValidToken(str_repeat('a',44)), 'an overlong trail token is refused');
$tokens=[];for($i=0;$i<50;$i++)$tokens[]=OrderTrail::newToken();
okv_test_eq(50,count(array_unique($tokens)),'trail token generation does not repeat across 50 samples');
