<?php
/** Task G review, grant, facility transition and payment-backed repayment. */
require_once dirname(__DIR__,2).'/includes/bootstrap.php';$t=0;$p=0;
function cad_ok($v,$l){global$t,$p;$t++;if($v){$p++;}else{fwrite(STDERR," FAIL: $l\n");}}function cad_eq($e,$a,$l){cad_ok($e===$a,$l);}
function cad_no($fn,$c,$l){try{$fn();cad_ok(false,$l);}catch(DomainException$e){cad_eq($c,$e->getMessage(),$l);}}
$s=bin2hex(random_bytes(4));$u=[];$b=[];$orders=[];
try{foreach(['A','B','Staff']as$i=>$n){$type=$i===2?'staff':'business';Database::run('INSERT INTO users(first_name,last_name,email,phone,password_hash,user_type,status)VALUES(:f,:l,:e,:p,:h,:t,:s)',[':f'=>$n,':l'=>'Credit',':e'=>"cad-$i-$s@example.test",':p'=>'+23468'.random_int(10000000,99999999),':h'=>password_hash('x',PASSWORD_BCRYPT),':t'=>$type,':s'=>'active']);$u[$i]=(int)Database::getInstance()->getConnection()->lastInsertId();if($i<2){Database::run('INSERT INTO business_customers(user_id,business_name,contact_person)VALUES(:u,:n,:c)',[':u'=>$u[$i],':n'=>"$n Credit $s",':c'=>$n]);$b[$i]=(int)Database::getInstance()->getConnection()->lastInsertId();}}
$input=['requested_days'=>'10','requested_limit'=>'500,000','reason'=>'Produce buying for our restaurant every working week.'];$a=Credit::apply($u[0],$input);$d=Credit::approveApplication($a['id'],$u[2],10,'400,000');cad_ok(!$d['already'],'a pending application is approved');cad_ok(Credit::approveApplication($a['id'],$u[2],10,'400,000')['already'],'an identical approval retry is idempotent');cad_no(fn()=>Credit::approveApplication($a['id'],$u[2],7,'300,000'),'conflicting_review','a conflicting approval retry is refused');
$bb=Credit::apply($u[1],$input);Credit::declineApplication($bb['id'],$u[2],'More trading history is needed.');cad_eq('declined',Database::one('SELECT status FROM credit_applications WHERE id=:id',[':id'=>$bb['id']])['status'],'decline closes the application');$bb2=Credit::apply($u[1],$input);Credit::grant($b[1],$u[2],7,'300,000');cad_eq('approved',Database::one('SELECT status FROM credit_applications WHERE id=:id',[':id'=>$bb2['id']])['status'],'manual grant approves a pending application');
Credit::changeTerms($b[1],8,'350,000');Credit::transitionFacility($b[1],'suspended');cad_eq('suspended',Database::one('SELECT credit_status FROM business_customers WHERE id=:id',[':id'=>$b[1]])['credit_status'],'approved credit can be suspended');Credit::transitionFacility($b[1],'approved');Credit::transitionFacility($b[1],'withdrawn');cad_no(fn()=>Credit::transitionFacility($b[1],'approved'),'invalid_transition','withdrawn credit is not directly reinstated');Credit::grant($b[1],$u[2],8,'350,000');
Database::run('INSERT INTO credit_transactions(business_customer_id,transaction_type,amount_subunit,due_date,status)VALUES(:b,:t,:a,:d,:s)',[':b'=>$b[1],':t'=>'charge',':a'=>10000000,':d'=>date('Y-m-d',strtotime('+7 days')),':s'=>'posted']);Database::run('INSERT INTO orders(order_number,user_id,customer_type,order_status,payment_option,payment_status,subtotal_subunit,order_total_subunit,amount_paid_subunit,balance_due_subunit,preferred_delivery_date)VALUES(:n,:u,:ct,:os,:po,:ps,:st,:ot,:ap,:bd,:dd)',[':n'=>"CAD-$s",':u'=>$u[1],':ct'=>'business',':os'=>'confirmed',':po'=>'on_account',':ps'=>'part_paid',':st'=>10000000,':ot'=>10000000,':ap'=>3000000,':bd'=>7000000,':dd'=>date('Y-m-d',strtotime('+7 days'))]);$oid=(int)Database::getInstance()->getConnection()->lastInsertId();$orders[]=$oid;Database::run('INSERT INTO payments(payment_number,user_id,order_id,provider,payment_type,expected_amount_subunit,paid_amount_subunit,status,confirmed_at)VALUES(:n,:u,:o,:p,:t,:e,:a,:s,NOW())',[':n'=>"CAD-P-$s",':u'=>$u[1],':o'=>$oid,':p'=>'manual',':t'=>'credit_repayment',':e'=>3000000,':a'=>3000000,':s'=>'paid']);$pid=(int)Database::getInstance()->getConnection()->lastInsertId();$r=Credit::recordRepayment($b[1],$pid);cad_eq(3000000,$r['amount_subunit'],'repayment uses the payment net amount');cad_no(fn()=>Credit::recordRepayment($b[1],$pid),'repayment_recorded','one payment cannot credit the journal twice');cad_eq(7000000,Credit::summaryForBusiness(Database::one('SELECT * FROM business_customers WHERE id=:id',[':id'=>$b[1]]))['outstanding_subunit'],'repayment frees the correct credit');cad_ok(count(Credit::ageing())>=2,'ageing returns managed credit accounts');
}finally{foreach($b as$id){Database::run('DELETE FROM credit_transactions WHERE business_customer_id=:id',[':id'=>$id]);Database::run('DELETE FROM credit_applications WHERE business_customer_id=:id',[':id'=>$id]);}foreach($orders as$id){Database::run('DELETE FROM payments WHERE order_id=:id',[':id'=>$id]);Database::run('DELETE FROM orders WHERE id=:id',[':id'=>$id]);}foreach($b as$id){Database::run('DELETE FROM business_customers WHERE id=:id',[':id'=>$id]);}foreach($u as$id){Database::run('DELETE FROM users WHERE id=:id',[':id'=>$id]);}}
fwrite(STDOUT,"\n$p / $t credit admin assertions passed.\n");exit($p===$t?0:1);
