<?php
/** Credit applications, facility controls, repayments and simple ageing. */
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/components/pagination.php';
Rbac::requirePermission('credit.view');
$search=trim((string)okv_input('search',''));$status=trim((string)okv_input('status','pending'));$page=(int)okv_input('page',1);
$queue=Credit::adminApplications($search,$status,$page);$selectedId=(int)okv_input('application',0);$selected=$selectedId?Credit::applicationForAdmin($selectedId):null;$ageing=Credit::ageing();
$businesses=Rbac::can('credit.grant')?Database::all('SELECT bc.id,bc.business_name,bc.credit_status FROM business_customers bc ORDER BY bc.business_name'):[];
$urlFor=static function(int $p)use($queue):string{$q=array_filter(['search'=>$queue['search'],'status'=>$queue['status'],'page'=>$p>1?$p:null],static fn($v)=>$v!==''&&$v!==null);return '/admin/credit.php'.($q?'?'.http_build_query($q):'');};
$okv_admin_title='Credit';$okv_admin_note='Applications, facility terms, repayments and what each business owes.';require __DIR__.'/../includes/components/admin/header.php';
?>
<?php if(okv_input('saved','')!==''):?><p class="okv-note-ok mb-5" role="status">The credit record has been updated.</p><?php endif;?>
<?php if(okv_input('error','')!==''):?><p class="okv-note-bad mb-5" role="alert"><?=okv_e(Credit::message((string)okv_input('error','')))?></p><?php endif;?>
<form method="get" class="mb-5 grid gap-3 rounded-md border border-mist bg-white p-4 sm:grid-cols-3"><div><label class="okv-label" for="credit-search">Business or email</label><input class="okv-input" id="credit-search" name="search" value="<?=okv_e($queue['search'])?>"></div><div><label class="okv-label" for="credit-status">Application status</label><select class="okv-input" id="credit-status" name="status"><option value="">All</option><?php foreach(Credit::APPLICATION_STATES as $s):?><option value="<?=okv_e($s)?>" <?=$queue['status']===$s?'selected':''?>><?=okv_e(ucfirst($s))?></option><?php endforeach;?></select></div><button class="okv-btn self-end" type="submit">Filter applications</button></form>
<div class="grid gap-5 xl:grid-cols-2">
 <section class="okv-panel" aria-labelledby="applications-heading"><div class="okv-panel-head"><h2 id="applications-heading" class="okv-panel-title">Credit applications</h2><span class="text-sm text-ink-60"><?=(int)$queue['count']?> total</span></div><?php if(!$queue['applications']):?><p class="p-5 text-sm text-ink-60">No applications match these filters.</p><?php else:?><ul class="divide-y divide-mist"><?php foreach($queue['applications'] as $app):?><li><a class="block min-h-[44px] px-4 py-3 hover:bg-forest-tint" href="/admin/credit.php?<?=okv_e(http_build_query(['search'=>$queue['search'],'status'=>$queue['status'],'page'=>$queue['page'],'application'=>$app['id']]))?>"><span class="flex justify-between gap-3"><strong><?=okv_e($app['business_name'])?></strong><span class="okv-badge <?=$app['status']==='pending'?'okv-badge-warn':'okv-badge-neutral'?>"><?=okv_e(ucfirst($app['status']))?></span></span><span class="mt-1 block text-sm text-ink-60"><?=okv_e(Money::format((int)$app['requested_limit_subunit']))?>, <?=(int)$app['requested_days']?> days</span></a></li><?php endforeach;?></ul><?php okv_pagination($queue['page'],$queue['last_page'],$urlFor,'Credit application pages');endif;?></section>
 <section class="okv-panel" aria-labelledby="review-heading"><div class="okv-panel-head"><h2 id="review-heading" class="okv-panel-title">Application review</h2></div><div class="okv-panel-body"><?php if(!$selected):?><p class="text-sm text-ink-60">Choose an application to review its request and account.</p><?php else:?><dl class="grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-ink-60">Business</dt><dd><?=okv_e($selected['business_name'])?></dd></div><div><dt class="text-ink-60">Email</dt><dd><?=okv_e($selected['email'])?></dd></div><div><dt class="text-ink-60">Requested</dt><dd class="font-mono"><?=okv_e(Money::format((int)$selected['requested_limit_subunit']))?></dd></div><div><dt class="text-ink-60">Terms</dt><dd><?=(int)$selected['requested_days']?> days</dd></div></dl><p class="mt-4 text-sm"><?=okv_e((string)$selected['reason'])?></p><a class="okv-btn-text mt-3" href="/admin/customers.php?customer=<?=(int)$selected['user_id']?>">Open customer account</a><?php if($selected['status']==='pending'&&Rbac::can('credit.apply.review')):?><div class="mt-5 grid gap-4 md:grid-cols-2"><form action="/api/v1/credit.php" method="post" class="space-y-3 rounded-md border border-mist p-3"><?=Csrf::field()?><input type="hidden" name="action" value="approve"><input type="hidden" name="application_id" value="<?=(int)$selected['id']?>"><div><label class="okv-label" for="approve-limit">Approved limit</label><input class="okv-input" id="approve-limit" name="credit_limit" required value="<?=okv_e(Money::format((int)$selected['requested_limit_subunit'],false,false))?>"></div><div><label class="okv-label" for="approve-days">Days</label><input class="okv-input" id="approve-days" name="credit_days" type="number" min="7" max="10" required value="<?=(int)$selected['requested_days']?>"></div><button class="okv-btn" type="submit">Approve credit</button></form><form action="/api/v1/credit.php" method="post" class="space-y-3 rounded-md border border-mist p-3"><?=Csrf::field()?><input type="hidden" name="action" value="decline"><input type="hidden" name="application_id" value="<?=(int)$selected['id']?>"><div><label class="okv-label" for="decline-reason">Reason for the customer</label><textarea class="okv-input" id="decline-reason" name="decision_reason" minlength="10" maxlength="1000" required></textarea></div><button class="okv-btn-outline border-tomato text-tomato" type="submit">Decline application</button></form></div><?php endif;endif;?></div></section>
</div>
<?php if(Rbac::can('credit.grant')):?><section class="okv-panel mt-5" aria-labelledby="grant-heading"><div class="okv-panel-head"><h2 id="grant-heading" class="okv-panel-title">Manual grant</h2></div><form action="/api/v1/credit.php" method="post" class="okv-panel-body grid gap-3 sm:grid-cols-4"><?=Csrf::field()?><input type="hidden" name="action" value="grant"><div><label class="okv-label" for="grant-business">Business</label><select class="okv-input" id="grant-business" name="business_id" required><?php foreach($businesses as $b):?><option value="<?=(int)$b['id']?>"><?=okv_e($b['business_name'])?>, <?=okv_e($b['credit_status'])?></option><?php endforeach;?></select></div><div><label class="okv-label" for="grant-limit">Limit</label><input class="okv-input" id="grant-limit" name="credit_limit" required></div><div><label class="okv-label" for="grant-days">Days</label><input class="okv-input" id="grant-days" name="credit_days" type="number" min="7" max="10" required></div><button class="okv-btn self-end" type="submit">Grant credit</button></form></section><?php endif;?>
<section class="okv-panel mt-5" aria-labelledby="ageing-heading"><div class="okv-panel-head"><h2 id="ageing-heading" class="okv-panel-title">Outstanding and overdue</h2></div><?php if(!$ageing):?><p class="p-5 text-sm text-ink-60">No business has an active or retained credit balance.</p><?php else:?><div class="overflow-x-auto"><table class="okv-table min-w-[48rem]"><thead><tr><th>Business</th><th>State</th><th>Outstanding</th><th>Overdue</th><th>Next due</th><th>Actions</th></tr></thead><tbody><?php foreach($ageing as $row):$s=$row['summary'];?><tr><td><a class="inline-flex min-h-[44px] items-center text-forest underline" href="/admin/customers.php?customer=<?=(int)$row['user_id']?>"><?=okv_e($row['business_name'])?></a></td><td><?=okv_e(ucfirst($row['credit_status']))?></td><td class="font-mono"><?=okv_e(Money::format((int)$s['outstanding_subunit']))?></td><td class="font-mono"><?=okv_e(Money::format((int)$s['overdue_subunit']))?></td><td><?=$s['earliest_due_date']?okv_e(date('j M Y',strtotime($s['earliest_due_date']))):'Nothing due'?></td><td><?php if(Rbac::can('credit.limit.set')):?><details><summary class="inline-flex min-h-[44px] cursor-pointer items-center text-forest underline">Manage</summary><div class="w-72 space-y-3 rounded-md border border-mist bg-white p-3"><form action="/api/v1/credit.php" method="post" class="space-y-2"><?=Csrf::field()?><input type="hidden" name="action" value="change_terms"><input type="hidden" name="business_id" value="<?=(int)$row['id']?>"><label class="okv-label">Limit<input class="okv-input" name="credit_limit" value="<?=okv_e(Money::format((int)$row['credit_limit_subunit'],false,false))?>" required></label><label class="okv-label">Days<input class="okv-input" name="credit_days" type="number" min="7" max="10" value="<?=(int)$row['credit_days']?>" required></label><button class="okv-btn-sm min-h-[44px]">Save terms</button></form><div class="flex flex-wrap gap-2"><?php foreach($row['credit_status']==='suspended'?['reinstate','withdraw']:['suspend','withdraw'] as $action):?><form action="/api/v1/credit.php" method="post"><?=Csrf::field()?><input type="hidden" name="action" value="<?=$action?>"><input type="hidden" name="business_id" value="<?=(int)$row['id']?>"><button class="okv-btn-text" type="submit"><?=okv_e(ucfirst($action))?></button></form><?php endforeach;?></div><form action="/api/v1/credit.php" method="post" class="space-y-2"><?=Csrf::field()?><input type="hidden" name="action" value="record_repayment"><input type="hidden" name="business_id" value="<?=(int)$row['id']?>"><label class="okv-label">Confirmed payment ID<input class="okv-input" name="payment_id" inputmode="numeric" required></label><button class="okv-btn-sm min-h-[44px]">Record repayment</button></form></div></details><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php require __DIR__.'/../includes/components/admin/footer.php';?>
